# Generated by Django 5.1.2 on 2025-01-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'managed': False},
        ),
    ]
