# Generated by Django 5.1.4 on 2025-01-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_manga_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manga',
            table='manga',
        ),
    ]
